### ISSUE TITLE
429 rate limit error message

### ISSUE THREAD

**Issue by jobrieniii** [540co/ads-bpa#210]
I really think this warning should not be a blocker on the screen.

Technically we aren't be rate limited b/c of 240 per minute - most likely because of the burst of requests in parallel.

(First time I hit the page I was rate limited this morning... so I know it wasn't because of a 240/minute.)

I would almost say we put some type of warning up in the top right corner that simply notes that we were rate limited on that given search and results may not be 100% accurate for that given search.

**Comment by jobrieniii** [comment]
Per discussion with @treyau21 - recommend only at this time remove the "reason" in the modal, and simply saying "yes, we were rate limited - here is a link to the rate limit policy - and maybe something about a shared  api key.

BTW, any word from openfda team @patricknowlan ?  we should explain exactly what we are seeing and see if they can explain vs. guessing.

**Comment by treyau21** [comment]
Agreed... and I'd assume we have different keys for https://dre.540.co and https://dre-dev.540.co.... probably a safe assumption since we have @killerbgt for devops.

Another note is that this is going to get worse once we add filtering per @patricknowlan .... if a fitler changes, it's just like doing another search.  So another 8 api calls every time the filters change.  I think the bottom line is that 240/minute is a ridiculously low rate limit and we are just going to hit it often if they don't give our prod api key a higher threshhold.

**Comment by treyau21** [comment]
This seems to have been fixed with the burst correction (only sending 6 or less requests in a burst)
